# Generated by Django 3.2.9 on 2022-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
